### ISSUE TITLE
Traefik [plugin] - failed to download plugin

### ISSUE THREAD

**Issue by brandonhowlett** [darkweak/souin#209]
I've configured the souin plugin instance per the traefik pilot instruction e.g.,

docker-compose.yml:

```
services:
  traefik: 
    ...
    command:
      ...
      - --experimental.plugins.souin.modulename=github.com/darkweak/souin
      - --experimental.plugins.souin.version=v1.6.6
      ...
    ...
```

Middlewares aside, I receive the following error crashing traefik:

```
traefik.go:79: command traefik error: failed to download plugin github.com/darkweak/souin: failed to write response: context deadline exceeded (Client.Timeout or context cancellation while reading body)
```
Is this a misconfiguration on my end? Traefik worked fine before including the plugin.

**Comment by darkweak** [comment]
Because of they added a timeout, sometimes they consider that Souin is not loaded as fast as their expectations. I planned a refactoring of Souin to have a faster boot.  
At the moment you have to retry again and again, there is no fix for that.

**Comment by brandonhowlett** [comment]
I see. I ran a loop script restarting traefik and after 50 iterations it still wouldn't download. Eagerly awaiting a solution. Thanks.

**Comment by yongzhang** [comment]
@darkweak can we build a custom image to include this plugin like described here: https://traefik.io/blog/using-private-plugins-in-traefik-proxy-2-5/

**Comment by darkweak** [comment]
Sorry @yongzhang I don't understand what you want to do and afaik I don't see the benefits of a custom image for træfik.
You can refer to the Souin documentation https://github.com/darkweak/souin#træfik-plugin or the Træfik plugin directory https://github.com/darkweak/souin/tree/master/plugins/traefik to run it. 

But if you really want a Dockerfile to build a custom Træfik image with Souin plugin, can you write a Dockerfile in the Træfik plugin directory and I will be delighted to merge it.
Anyway, this issue is a runtime issue, not a compiling issue because yægi thinks the plugin is not setup as fast as expected.

**Comment by yongzhang** [comment]
> Sorry @yongzhang I don't understand what you want to do and afaik I don't see the benefits of a custom image for træfik. You can refer to the Souin documentation [https://github.com/darkweak/souin#træfik-plugin](https://github.com/darkweak/souin#tr%C3%A6fik-plugin) or the Træfik plugin directory https://github.com/darkweak/souin/tree/master/plugins/traefik to run it.
> 
> But if you really want a Dockerfile to build a custom Træfik image with Souin plugin, can you write a Dockerfile in the Træfik plugin directory and I will be delighted to merge it. Anyway, this issue is a runtime issue, not a compiling issue because yægi thinks the plugin is not setup as fast as expected.

sorry I should describe my comment more clearly, I'm saying we may build a custom traefik image to pack the plugin to avoid network issues, like introduced [here](https://traefik.io/blog/using-private-plugins-in-traefik-proxy-2-5/), but I haven't tried yet, you know not everywhere in the world can access github, this may be the only way for us to use plugins.

**Comment by darkweak** [comment]
Okay I see. IMHO we could add a build inside the github actions to publish automatically the image to the dockerhub or any other docker image repository.

**Comment by darkweak** [comment]
I'll setup the built traefik docker image for the next minor version

**Comment by darkweak** [comment]
@yongzhang you can now use the https://hub.docker.com/repository/docker/darkweak/souin-traefik

**Comment by xZero707** [comment]
As of today, I still have similar issue, and it seems to be specific for this plugin. Other plugins load without an issue.
```
level=error msg="Plugins are disabled because an error has occurred." error="unable to set up plugins environment: unable to download plugin github.com/darkweak/souin: error: 502: Bad Gateway"
```
Not sure how is this occurring? GitHub error?
I've tried manually specifying DNS revolvers for Traefik container, recreating network, etc, and still cannot make it work.

**Comment by darkweak** [comment]
Hello @xZero707 what's your config? Did you try to load the plugin with `github.com/darkweak/souin` or `github.com/darkweak/souin/plugins/traefik`?

**Comment by darkweak** [comment]
@xZero707 nevermind, they have some troubles on some plugins. If I try to load Souin with the traffic v3+ it gets a `Bad gateway` from their servers and throws this error in the logs
```
2023-07-29T08:22:43Z ERR github.com/traefik/traefik/v3/cmd/traefik/traefik.go:216 > Plugins are disabled because an error has occurred. error="unable to set up plugins environment: unable to download plugin github.com/darkweak/souin: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/darkweak/souin/v1.6.39\": GET https://plugins.traefik.io/public/download/github.com/darkweak/souin/v1.6.39 giving up after 4 attempt(s)"
```

I think this issue must be reported on the Traefik repository instead of the Souin one because it compiles well on the CI to generate the Træfik docker image with Souin embedded inside and E2E tests are working too on the Træfik integration.

**Comment by darkweak** [comment]
@xZero707 it should work now

**Comment by tvbird** [comment]
The error is still there (Traefik 2.10)

> level=debug msg="loading of plugin: souin: github.com/darkweak/souin@v1.6.41"
level=error msg="Plugins are disabled because an error has occurred." error="unable to set up plugins environment: unable to download plugin github.com/darkweak/souin: error: 502: Bad Gateway"
